name: Create Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Test and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get current version
        id: current_version
        uses: ncipollo/semantic-version-action@v1

      - name: Next Version
        uses: vemel/nextversion@0.1.1
        with:
          version: ${{ steps.current_version.outputs.semver  }}
        id: next_version

      - name: Show next version
        run: echo ${{ steps.next_version.outputs.minor  }}
